credentials:
  usernames:
    jsmith:
      email: jsmith@gmail.com
      name: John Smith
      password: $2b$12$2RzmDEuv/3Pj0XKab1Xr0uQNYy.noHmIWT5o7WqzUXpHofuWsa296
    rbriggs:
      email: rbriggs@gmail.com
      name: Rebecca Briggs
      password: $2b$12$Iw0csjN55zTUuaDOSRUTiOC9yX.nMj9DNA8Q4Qd8LuKgDhDqmHxJ2 
cookie:
  expiry_days: 30
  key: random_signature_key # Must be string
  name: random_cookie_name
preauthorized:
  emails:
  - melsby@gmail.com



